apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-portal-ui
  labels:
    app: banking-portal-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-portal-ui
  template:
    metadata:
      labels:
        app: banking-portal-ui
    spec:
      containers:
      - name: banking-portal-ui
        image: default-route-openshift-image-registry.apps.rm2.thpm.p1.openshiftapps.com/code-cadets-dev/banking-portal-ui:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: banking-portal-ui
spec:
  selector:
    app: banking-portal-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # No LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: banking-portal-ui
spec:
  to:
    kind: Service
    name: banking-portal-ui
  port:
    targetPort: 8080
  tls:
    termination: edge
